apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: PORT
          value: "{{ .Values.containerPort }}"
        {{- if .Values.postgres.secretName }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.secretName }}
              key: uri
        {{- end }}
