apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: PORT
          value: "{{ .Values.containerPort }}"
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgres.appUser }}:{{ .Values.postgres.appPassword }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ include "example-app.dbName" . }}"
